function output = Anisotropic_defusion(input,m,gamma)
import tools.*

output = imdiffuse(abs(input), 'tad', ...
                      'scheme', 'implicit', ...
                      'nsteps',m, ...
                      'gamma',  gamma, ...
                      'boundary', 'mirror');
end